// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApp.Data;

#nullable disable

namespace RestaurantApp.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260425134648_AddAktivanToZaposlenik")]
    partial class AddAktivanToZaposlenik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantApp.Models.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Dostupno")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jela");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 9.50m,
                            Dostupno = true,
                            Naziv = "Margherita Pizza",
                            Opis = "Klasična pizza s rajčicom i mozzarellom",
                            Vrsta = "Hrana"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 8.00m,
                            Dostupno = true,
                            Naziv = "Hamburger",
                            Opis = "Goveđi burger s povrćem",
                            Vrsta = "Hrana"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 2.50m,
                            Dostupno = true,
                            Naziv = "Coca Cola",
                            Opis = "0.33l",
                            Vrsta = "Piće"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 10.00m,
                            Dostupno = true,
                            Naziv = "Pasta Carbonara",
                            Opis = "Kremasta pasta s pancetom",
                            Vrsta = "Hrana"
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 3.00m,
                            Dostupno = true,
                            Naziv = "Sok od naranče",
                            Opis = "Svježe cijeđeni",
                            Vrsta = "Piće"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Models.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NacinPreuzimanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredvijenoVrijemeDostave")
                        .HasColumnType("int");

                    b.Property<string>("RazlogOdbijanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZaposlenikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZaposlenikId");

                    b.ToTable("Narudzbe");
                });

            modelBuilder.Entity("RestaurantApp.Models.StavkaNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaStavke")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkeNarudzbe");
                });

            modelBuilder.Entity("RestaurantApp.Models.Zaposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zaposlenici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Ime = "Admin",
                            KorisnickoIme = "admin",
                            Lozinka = "admin123",
                            Prezime = "Admin",
                            Uloga = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Aktivan = true,
                            Ime = "Pero",
                            KorisnickoIme = "pero",
                            Lozinka = "pero123",
                            Prezime = "Perić",
                            Uloga = "Zaposlenik"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Models.Narudzba", b =>
                {
                    b.HasOne("RestaurantApp.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("Narudzbe")
                        .HasForeignKey("ZaposlenikId");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("RestaurantApp.Models.StavkaNarudzbe", b =>
                {
                    b.HasOne("RestaurantApp.Models.Jelo", "Jelo")
                        .WithMany("Stavke")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Models.Narudzba", "Narudzba")
                        .WithMany("Stavke")
                        .HasForeignKey("NarudzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("RestaurantApp.Models.Jelo", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("RestaurantApp.Models.Narudzba", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("RestaurantApp.Models.Zaposlenik", b =>
                {
                    b.Navigation("Narudzbe");
                });
#pragma warning restore 612, 618
        }
    }
}
